MY DEAREST MAGGI,

PLEASE FIX THE OIL SPILL. IT IS STARTING TO RUIN THE SURROUNDING WATER OF MY DOMAIN. MY LITTLE CREATURES NEED WATER TO LIVE. I AM STILL RECOVERING FROM MY INJURIES. THANK YOU FOR ASKING (BEWARE OF SARCASM). 
ALSO COULD YOU PLEASE STOP MAKING MORE MUSHROOMS? THEIR SPORES ARE STARTING TO MAKE MY CREATURES MAKE THESE SEMI-AUTONOMOUS, CONVULSIVE EXPULSIONS OF AIR THROUGH THEIR MOUTHS AND NOSES. 

LOVE, BITSY 