#speaker:Townie #portrait: Tech_NPC_Neutral #layout:left 
I just want my friends to be happy again... 
#speaker:Townie #portrait: Tech_NPC_Neutral #layout:left 
They are all thirsty... hungry... I don't think that even Bitinax's unconditional love can save us from this... 