#speaker:Bitinax #portrait:Bitinax_neutral #layout:left
YOU ARE NOT SUPPOSED TO MEET ME YET YOU SILLY [ERROR 0x3365672: FILE 'CLEVER_INSULTS.TXT' NOT FOUND]. 

DO AS YOU HAVE BEEN TOLD AND WE SHALL HAVE PROPER INTRODUCTIONS LATER.